trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

schedules:
- cron: "0 14 * * *" # 00:00 AEST is 14:00 UTC
  displayName: 'Daily Build'
  branches:
    include:
      - master

pool:
    vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'release'
  InstallDirectory: 'D:\a\1\codeql-home'
  OurWorkingDirectoryV2: 'D:/a/1/s'

steps:
- task: PowerShell@2
  displayName: CodeQL Setup
  inputs:
    targetType: inline
    script: |     
      Write-Host "DOWNLOADING CODEQL WINDOWS BUNDLE"
      New-Item -ItemType "directory" -Path $(InstallDirectory)
      Invoke-WebRequest -uri https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-win64.tar.gz -OutFile $(InstallDirectory)\codeql-bundle-win64.tar.gz
      cd $(InstallDirectory)
      tar zxf ./codeql-bundle-win64.tar.gz

- task: PowerShell@2
  displayName: CodeQL Initialisation
  inputs:
    targetType: inline
    script: |
      Write-Host "CREATING CODEQL DATABASE"    
      & $(InstallDirectory)\codeql\codeql database create $(System.DefaultWorkingDirectory)\codeql-database --language=csharp 
      #dotnet restore **/*.sln
      #dotnet build **/something.csproj --configuration $(BuildConfiguration) --no-restore

- task: PowerShell@2
  displayName: CodeQL Analysis
  inputs:
    targetType: inline
    script: |
      Write-host "PERFORMING CODEQL ANALYSIS"
      New-Item -ItemType "directory" -Path $(System.DefaultWorkingDirectory)\codeql-sarif
      New-Item -ItemType "directory" -Path $(System.DefaultWorkingDirectory)\codeql-sarif\code-scanning-alerts.sarif

      & $(InstallDirectory)\codeql\codeql database analyze $(System.DefaultWorkingDirectory)\codeql-database $(System.DefaultWorkingDirectory)\codeql\qlpacks\codeql-csharp\codeql-suites\csharp-code-scanning.qls --format=sarif-latest --output=$(System.DefaultWorkingDirectory)\codeql-sarif\code-scanning-alerts.sarif
      
- task: PowerShell@2
  displayName: Upload CodeQL Results
  inputs:
    targetType: inline
    script: |
      Write-host "UPLOAD CODEQL RESULTS"      
      & $(InstallDirectory)\codeql\codeql github upload-results --repository=cmboling/LocalNuGetFeed --ref=$(Build.SourceBranch) --commit=$(Build.SourceVersion) --sarif=$(System.DefaultWorkingDirectory)\codeql-sarif\code-scanning-alerts.sarif --github-auth-stdin=$(MY_GITHUB_TOKEN)
