name: issue-checklist


on:
  push:
  schedule:
    # Define your own schedule after "cron: "
    # Add a comment to the end of the line to read it in plain language 🕓
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
    - cron: 30 17 * * FRI # Every Friday at 17:30 UTC (5:30pm UTC / 9:30am PT)

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const query = `query($owner:String!, $name:String!, $label:String!) {
              repository(owner:$owner, name:$name){
                issues(first:100, labels: [ $label ]) {
                  nodes {
                    id
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              label: 'G: AdvSec'
            }
            const result = await github.graphql(query, variables)
            console.log(result)
            
            if (!result) {
               core.setFailed('GraphQL request failed')
             } else {
               var pocs = [];
               console.log(`POC Days per Issue:`)
               for (const nodeNum in result.node.cards.nodes) {
                 const node = result.node.cards.nodes[nodeNum]
                 pocs.push({id:node.content.id, url: node.content.url })
                 console.log(`${node.content.url}`)
               }
             return pocs 
             }
            
            
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: 1, # replace with the number of the specific issue the action will comment on
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `# Replace me with your own content!
              
              Use multiple lines of **Markdown** here to create your own templated issue comment.
              
              | Even | Tables | 
              | --- | --- |
              | If you | want to |
              
              Just keep the comment body between the backticks.
              `
            })
